//Contact Module const
export const FETCH_START = "fetch_start";
export const FETCH_SUCCESS = "fetch_success";
export const FETCH_ERROR = "fetch_error";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";

//Auth const
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNIN_GOOGLE_USER = "SIGNIN_GOOGLE_USER";
export const SIGNIN_GOOGLE_USER_SUCCESS = "SIGNIN_GOOGLE_USER_SUCCESS";
export const SIGNIN_FACEBOOK_USER = "SIGNIN_FACEBOOK_USER";
export const SIGNIN_FACEBOOK_USER_SUCCESS = "SIGNIN_FACEBOOK_USER_SUCCESS";
export const SIGNIN_TWITTER_USER = "SIGNIN_TWITTER_USER";
export const SIGNIN_TWITTER_USER_SUCCESS = "SIGNIN_TWITTER_USER_SUCCESS";
export const SIGNIN_GITHUB_USER = "SIGNIN_GITHUB_USER";
export const SIGNIN_GITHUB_USER_SUCCESS = "signin_github_user_success";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const INIT_URL = "INIT_URL";
export const USER_DATA = "user_data";
export const USER_TOKEN_SET = "user_token_set";

// Category Const
export const GET_DATA_CATE = "GET_DATA_CATE";
export const GET_DATA = "GET_DATA";
export const GET_ALL_DATA_CATE = "GET_ALL_DATA_CATE";
export const FILTER_DATA = "FILTER_DATA";
export const GET_ALL_DATA_NOSUBCATE = "GET_ALL_DATA_NOSUBCATE";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

/* ROLE */
export const GET_ALL_DATA_ROLE = "GET_ALL_DATA_ROLE";
export const GET_DETAIL_ROLE = "GET_DETAIL_ROLE";
export const DELETE_USER_ROLE = "DELETE_USER_ROLE";
export const DELETE_ROLE_HAS_PERMISSION = "DELETE_ROLE_HAS_PERMISSION";
export const SEARCH_PERMISSION = "SEARCH_PERMISSION";
export const SEARCH_USER = "SEARCH_USER";
export const ADD_PERMISSION_ROLE = "ADD_PERMISSION_ROLE";
export const ADD_USER_ROLE = "ADD_USER_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_MULTIPLE_ROLE = "DELETE_MULTIPLE_ROLE";
export const ADD_ROLE = "ADD_ROLE";
/* MEDIA */
export const GET_ALL_FILES = "GET_ALL_FILES";
export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_MULTIPLE_FILES = "UPLOAD_MULTIPLE_FILES";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const DELETE_FILES = "DELETE_FILES";
export const DELETE_FOLDER = "DELETE_FOLDER";

export const SET_UPLOAD_FILE = "SET_UPLOAD_FILE";
export const REFRESH_UPLOAD_FILE = "REFRESH_UPLOAD_FILE";
export const SUCCESS_UPLOAD_FILE = "SUCCESS_UPLOAD_FILE";
export const SET_UPLOAD_PROGRESS = "SET_UPLOAD_PROGRESS";
export const FAILURE_UPLOAD_FILE = "FAILURE_UPLOAD_FILE";

/* PERMISSION */

export const GET_ALL_PERMISSION = "GET_ALL_PERMISSION";
export const DELETE_PERMISSION = "DELETE_PERMISSION";
export const DELETE_MULTIPLE_PERMISSION = "DELETE_MULTIPLE_PERMISSION";
export const UPDATE_PERMISSION = "UPDATE_PERMISSION";
export const ADD_PERMISSION = "ADD_PERMISSION";
export const GET_ALL_MODULE = "GET_ALL_MODULE";
export const GET_ALL_PERMISSION_TYPE = "GET_ALL_PERMISSION_TYPE";
export const FILTER_PERMISSION = "FILTER_PERMISSION";

/* USER */

export const GET_ALL_USER = "GET_ALL_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";

/*FILES */
